// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {types} from '../models';

export function ConnectToDB(arg1:storage.Config):Promise<void>;

export function CreateMasterMaps(arg1:string):Promise<void>;

export function DeleteMasterMap(arg1:string):Promise<void>;

export function DisconnectDB(arg1:storage.Config):Promise<void>;

export function GetExtent(arg1:string):Promise<types.Extent>;

export function GetMasterMaps():Promise<Array<types.MasterMap>>;

export function LoadDbConfig():Promise<storage.Config>;

export function ProcessFiles(arg1:Array<string>,arg2:string,arg3:string,arg4:string):Promise<Array<string>>;

export function SaveDbConfig(arg1:storage.Config):Promise<void>;

export function SelectFiles():Promise<Array<string>>;

export function SelectGeojsonFile():Promise<string>;

export function SelectGeojsonFileForGeoreference(arg1:string):Promise<string>;
