// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToDB(arg1) {
  return window['go']['main']['App']['ConnectToDB'](arg1);
}

export function CreateMasterMaps(arg1) {
  return window['go']['main']['App']['CreateMasterMaps'](arg1);
}

export function DeleteMasterMap(arg1) {
  return window['go']['main']['App']['DeleteMasterMap'](arg1);
}

export function DisconnectDB(arg1) {
  return window['go']['main']['App']['DisconnectDB'](arg1);
}

export function GeoreferenceWorker(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GeoreferenceWorker'](arg1, arg2, arg3, arg4, arg5);
}

export function GetExtent(arg1) {
  return window['go']['main']['App']['GetExtent'](arg1);
}

export function GetMasterMaps() {
  return window['go']['main']['App']['GetMasterMaps']();
}

export function LoadDbConfig() {
  return window['go']['main']['App']['LoadDbConfig']();
}

export function ProcessGeoreference(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProcessGeoreference'](arg1, arg2, arg3, arg4);
}

export function SaveDbConfig(arg1) {
  return window['go']['main']['App']['SaveDbConfig'](arg1);
}

export function SelectGeojsonFile() {
  return window['go']['main']['App']['SelectGeojsonFile']();
}

export function SelectGeojsonFileForGeoreference(arg1) {
  return window['go']['main']['App']['SelectGeojsonFileForGeoreference'](arg1);
}

export function SelectRasterFiles() {
  return window['go']['main']['App']['SelectRasterFiles']();
}
